-- MySQL Script generated by MySQL Workbench
-- Sam 02 Jun 2018 19:10:08 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db_topo
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `db_topo` ;

-- -----------------------------------------------------
-- Schema db_topo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_topo` DEFAULT CHARACTER SET utf8 ;
USE `db_topo` ;

-- -----------------------------------------------------
-- Table `db_topo`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_topo`.`user` ;

CREATE TABLE IF NOT EXISTS `db_topo`.`user` (
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP);


-- -----------------------------------------------------
-- Table `db_topo`.`Utilisateur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_topo`.`Utilisateur` ;

CREATE TABLE IF NOT EXISTS `db_topo`.`Utilisateur` (
  `id` INT NOT NULL,
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `db_topo`.`Location`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_topo`.`Location` ;

CREATE TABLE IF NOT EXISTS `db_topo`.`Location` (
  `idLocation` INT NOT NULL,
  `proprio` VARCHAR(45) NULL,
  `emprunteur` VARCHAR(45) NULL,
  `datedeb` DATE NULL,
  `datefin` DATE NULL,
  `Utilisateur_id` INT NOT NULL,
  PRIMARY KEY (`idLocation`, `Utilisateur_id`),
  INDEX `fk_Location_Utilisateur1_idx` (`Utilisateur_id` ASC),
  CONSTRAINT `fk_Location_Utilisateur1`
    FOREIGN KEY (`Utilisateur_id`)
    REFERENCES `db_topo`.`Utilisateur` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `db_topo`.`Topo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_topo`.`Topo` ;

CREATE TABLE IF NOT EXISTS `db_topo`.`Topo` (
  `idTopo` INT NOT NULL,
  `secteur` VARCHAR(45) NOT NULL,
  `voie` VARCHAR(45) NULL,
  `hauteur` VARCHAR(45) NULL,
  `cotation` VARCHAR(45) NULL,
  `points` VARCHAR(45) NULL,
  `Location_idLocation` INT NOT NULL,
  `Location_Utilisateur_id` INT NOT NULL,
  PRIMARY KEY (`idTopo`, `Location_idLocation`, `Location_Utilisateur_id`),
  INDEX `fk_Topo_Location1_idx` (`Location_idLocation` ASC, `Location_Utilisateur_id` ASC),
  CONSTRAINT `fk_Topo_Location1`
    FOREIGN KEY (`Location_idLocation` , `Location_Utilisateur_id`)
    REFERENCES `db_topo`.`Location` (`idLocation` , `Utilisateur_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `db_topo`.`Commentaire`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_topo`.`Commentaire` ;

CREATE TABLE IF NOT EXISTS `db_topo`.`Commentaire` (
  `category_id` INT NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `Utilisateur_id` INT NOT NULL,
  `Topo_idTopo` INT NOT NULL,
  PRIMARY KEY (`category_id`, `Utilisateur_id`, `Topo_idTopo`),
  INDEX `fk_Commentaire_Utilisateur_idx` (`Utilisateur_id` ASC),
  INDEX `fk_Commentaire_Topo1_idx` (`Topo_idTopo` ASC),
  CONSTRAINT `fk_Commentaire_Utilisateur`
    FOREIGN KEY (`Utilisateur_id`)
    REFERENCES `db_topo`.`Utilisateur` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Commentaire_Topo1`
    FOREIGN KEY (`Topo_idTopo`)
    REFERENCES `db_topo`.`Topo` (`idTopo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
